name: Build

on:
  repository_dispatch:
    types: [build-trigger]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Get tag version
        id: get_version
        run: |
          GITHUB_REF=${{ github.event.client_payload.ref }}
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
      - name: Set artifact file name
        id: file_name
        run: |
          echo ::set-output name=ARTIFACT_FILE_NAME::semantic-release-test_v${{ steps.get_version.outputs.VERSION }}.tar.gz
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: ${{ github.event.client_payload.ref }}
      - name: Create tar.gz
        run: |
          echo "${{ steps.get_version.outputs.VERSION }}"
          echo "${{ steps.file_name.outputs.ARTIFACT_FILE_NAME }}"
          echo "${{ github.event.client_payload.release.id }}"
          echo "${{ github.event.client_payload.release.upload_url }}"
          echo "${{ github.event.client_payload.release.html_url }}"

          tar --exclude="${{ steps.file_name.outputs.ARTIFACT_FILE_NAME }}" -czf "${{ steps.file_name.outputs.ARTIFACT_FILE_NAME }}" .
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: semantic-release-test
          path: ${{ steps.file_name.outputs.ARTIFACT_FILE_NAME }}
          retention-days: 1
