name: Github Release Draft

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Get Notes
        id: get_notes
        run: |
          export NOTES=`git show -1 --no-notes --no-patch | tail +7`
          echo echo ::set-output name=NOTES::${NOTES}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          body: ${{ steps.get_notes.outputs.NOTES }}
