name: Run on published

on:
  release:
    types: [published]

jobs:
  run-on-published:
    runs-on: ubuntu-20.04
    steps:
      - name: Get tag version
        id: get_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Download all release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Version ${{ steps.get_version.outputs.VERSION }} was published."
          echo ${{ steps.get_release.outputs.id }}

          URL="https://api.github.com/repos/rickbassham/semantic-release-test/releases/${{ steps.get_release.outputs.id }}"
          echo ${URL}

          ASSETS=$(curl -H "Authorization: token ${GITHUB_TOKEN}" ${URL} | jq --raw-output '.assets[] | [ .id, .name ] | @tsv')
          echo "${ASSETS}"

          echo "${ASSETS}" |
              while IFS=$'\t' read -r id name; do
                wget -q --auth-no-challenge --header="Accept:application/octet-stream" -O "${name}" \
                  "https://${GITHUB_TOKEN}:@api.github.com/repos/rickbassham/semantic-release-test/releases/assets/${id}"
              done

          ls -al
